substitutions:

  _DOCKER_COMPOSE_VERSION: 1.25.5

steps:

- id: "Rodando docker-compose"
  # name: 'docker/compose:${_DOCKER_COMPOSE_VERSION}'
  name: 'gcr.io/${PROJECT_ID}/docker-compose:${_DOCKER_COMPOSE_VERSION}'  
  args: ['-f', 'docker-compose.yaml', '-f', 'docker-compose.cloudbuild.yaml', 'up', '--detach', '--build']

- id: "Rodando docker ps"
  name: 'gcr.io/cloud-builders/docker'
  args: ['ps']

- id: "Mudando user da pasta /var/www"
  name: 'gcr.io/cloud-builders/docker'
  args: ['exec', '-t', '-u', 'root', 'app', 'chown', '-R', 'www-data', '/var/www']

- id: "Verificando environment variables"
  name: 'gcr.io/cloud-builders/docker'
  args: ['exec', '-t', 'app', 'printenv' ]

- id: "Listando arquivos de /var/www"
  name: 'gcr.io/cloud-builders/docker'
  args: ['exec', '-t', 'app', 'ls', '-laht', '/var/www']

- id: "Rodando composer"
  name: 'gcr.io/cloud-builders/docker'
  args: ['exec', '-t', 'app', 'composer', 'install']

- id: "Copiando .env"
  name: 'gcr.io/cloud-builders/docker'
  args: ['exec', '-t', 'app', 'cp', '.env.example', '.env']

- id: "Rodando key:generate"
  name: 'gcr.io/cloud-builders/docker'
  args: ['exec', '-t', 'app', 'php', '/var/www/artisan', 'key:generate']

- id: "Rodando migrations"
  name: 'gcr.io/cloud-builders/docker'
  args: ['exec', '-t', 'app', 'php', '/var/www/artisan', 'migrate']

- id: "Rodando phpunit"
  name: 'gcr.io/cloud-builders/docker'
  args: ['exec', '-t', 'app', 'php', '/var/www/vendor/bin/phpunit', '-c', '/var/www/phpunit.xml']

- id: "Obtendo versão do Docker"
  name: 'gcr.io/cloud-builders/docker'
  args: [ 'version' ]
  env: [ 'DOCKER_CLI_EXPERIMENTAL=enabled' ]

- id: "Building image from Dockerfile.prod.build"
  name: 'gcr.io/cloud-builders/docker'
  args: [ 'build', '-t', 'gcr.io/${PROJECT_ID}/app-laravel:${SHORT_SHA}', '-f', 'Dockerfile.prod.build', '.']
  env:
    - 'DOCKER_CLI_EXPERIMENTAL=enabled'

- id: "Pushing image"
  name: 'gcr.io/cloud-builders/docker'
  args: [ 'push', 'gcr.io/${PROJECT_ID}/app-laravel:${SHORT_SHA}' ]

- id: "Adjusting deployment file - k8s"
  name: 'gcr.io/cloud-builders/gcloud'
  entrypoint: '/bin/sh'
  args:
    - '-c'
    - |
      sed -i 's#img-app-deployment#gcr.io/${PROJECT_ID}/app-laravel:${SHORT_SHA}#g' ./k8s/app/deployment.yaml
      cat ./k8s/app/deployment.yaml

- id: "Deploying K8s"
  name: 'gcr.io/cloud-builders/kubectl'
  args:
    - 'apply'
    - '-f'
    - './k8s/app/deployment.yaml'
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
    - 'CLOUDSDK_CONTAINER_CLUSTER=cluster-docker-laravel'